# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 09:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_model',
            fields=[
                ('uuid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(default='None', max_length=50)),
                ('last_name', models.CharField(default='None', max_length=50)),
                ('email', models.EmailField(default='None', max_length=254)),
                ('password', models.CharField(default='abc123', max_length=150)),
                ('myself', models.CharField(default='None', max_length=300)),
                ('address', models.CharField(default='None', max_length=300)),
                ('mobilePh', models.CharField(default='None', max_length=20)),
                ('workPh', models.CharField(default='None', max_length=20)),
                ('workEmail', models.EmailField(max_length=254)),
                ('last_login', models.CharField(default='None', max_length=50)),
                ('profile_pic', models.ImageField(blank=True, default='None', upload_to=webApp.models.upload_location)),
            ],
            options={
                'db_table': 'user_model',
            },
        ),
        migrations.CreateModel(
            name='workprofile_model',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('workId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('designation', models.CharField(default='None', max_length=50)),
                ('organization', models.CharField(default='None', max_length=50)),
                ('period', models.CharField(default='None', max_length=50)),
                ('description', models.CharField(default='None', max_length=200)),
                ('user', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workprofile_model',
            },
        ),
    ]
